[tool.poetry]
name = "calculate-dcf"
version = "0.2.0"
description = ""
authors = ["kollerbud <kollerbud@gmail.com>"]
readme = "README.md"

packages = [
    { include = "app" },
    { include = "src" },
    { include = "tests" },
]

[tool.poetry.dependencies]
python = "^3.11"
streamlit = "^1.41.1"
requests = "^2.32.3"
bs4 = "^0.0.2"
duckdb = "^1.1.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
