FROM python:3.9

WORKDIR /news_dags

COPY . /news_dags/

RUN pip install -r requirements.txt
RUN apt-get update && \
    apt-get install nano

# Copy your code and workspace to /opt/dagster/app

ENV PYTHONPATH=/news_dags/src
ENV DAGSTER_HOME=/news_dags/

# Copy dagster instance YAML to $DAGSTER_HOME

EXPOSE 8080
