import duckdb
import pandas as pd
from pathlib import Path
from typing import Dict, List, Optional
from edgar import Company, set_identity
from edgar.xbrl import XBRLS
import re


set_identity('google@google.com')

class FinancialDataProcessor:

    METRIC_ALIASES = {
        'revenue': [
            "Contract Revenue",  "Total net revenue", "Revenue", "Net sales", "Net revenue",
            "Total net sales",
            "RevenueFromContractWithCustomerExcludingAssessedTax", "SalesRevenueNet"
        ],
        'operating_income': [
            "operating_income", "Operating Income", "Operating income",
            "Operating Income (Loss)", "OperatingIncomeLoss",
            "IncomeLossFromContinuingOperationsBeforeIncomeTaxes"
        ],
        'net_income': [
            "Profit or Loss", "Net Income", "Net income",
            "Net Income from Continuing Operations",
            "Basic Net Income Available to Common Shareholders", "NetIncomeLoss"
        ],
        'operating_cash_flow': [
            "operating_cash_flow", #1
            "Net Cash from Operating Activitie", #2
            "Net cash provided by (used in) operating activities", #3
            "Cash generated by operating activities", #4
            "Cash Provided by (Used in) Operating Activity, Continuing Operation, Total", #5
            "Net cash provided by operating activities" #6
        ],
        'capex': [
            "capex",
            "Capital expenditures",
            "Additions to property and equipment",
            "Payments to acquire property, plant and equipment",
            "Purchases of property, plant and equipment",
            "Purchases of property and equipment",
            "PaymentsToAcquirePropertyPlantAndEquipment",
            "Capital expenditures, including internal-use software",
        ],
        'interest_expense': [
            "Interest expense",
            "Interest expense, net", "Interest Expense (non-operating)",
            "InterestPaid"
        ],
        'tax_expense': [
            "tax_expense", "Income Tax Expense", "Income tax provision (benefit)",
            "Provision for Income Taxes", "Provision for (benefit from) income taxes",
            "IncomeTaxExpenseBenefit", "IncomeTaxPaid"
        ],
        'cash': [
            "cash", "Cash and cash equivalents", "Cash and Cash Equivalents",
            "Cash, cash equivalents and restricted cash",
            "CashAndCashEquivalentsAtCarryingValue"
        ],
        'equity': [
            "equity", "Total stockholders' equity", "Total stockholders’ equity",
            "Total equity", "Total shareholders' equity", "Shareholders' equity",
            "StockholdersEquity", "StockholdersEquityIncludingPortionAttributableToNoncontrollingInterest"
        ],
        'long_term_debt': [
            "long_term_debt", "Long Term Debt", "Long-Term Debt", "Long-term debt",
            "Long-term debt, net of current portion", "LongTermDebt", "LongTermDebtAndCapitalLeaseObligations"
        ],
        'short_term_debt': [
            "short_term_debt", "Short-term debt", "Short-term debt",
            "Current portion of long-term debt", "ShortTermDebt", "DebtCurrent"
        ],

        'shares_outstanding': [
            "shares_outstanding",
            "Diluted (in shares)",
            "Weighted average shares outstanding - diluted",
            "Weighted-average shares outstanding - diluted",
            "Shares Outstanding (Diluted)", "EntityCommonStockSharesOutstanding",
            "CommonStockSharesOutstanding", "WeightedAverageNumberOfDilutedSharesOutstanding",
            "Weighted average shares outstanding, diluted",
        ]
    }

    # Constrain metrics to their correct financial statement to prevent
    # cross-statement mismatches (e.g. pulling balance sheet PP&E as capex)
    METRIC_STATEMENT_TYPE = {
        'revenue':             'Income Statement',
        'operating_income':    'Income Statement',
        'net_income':          'Income Statement',
        'interest_expense':    'Income Statement',
        'tax_expense':         'Income Statement',
        'operating_cash_flow': 'Cash Flow',
        'capex':               'Cash Flow',
        'cash':                'Balance Sheet',
        'equity':              'Balance Sheet',
        'long_term_debt':      'Balance Sheet',
        'short_term_debt':     'Balance Sheet',
        'shares_outstanding':  'Income Statement',  # usually on the face of the IS
    }

    # Negative-keyword filters to prevent false-positive fuzzy matches.
    # If a DB concept_id contains ANY of these substrings (case-insensitive),
    # it will be excluded from fuzzy matching for that metric.
    METRIC_EXCLUDE_PATTERNS = {
        'shares_outstanding': ['per share', 'earnings', 'eps', 'per common'],
        'capex':              ['depreciation', 'accumulated', 'net'],
        'net_income':         ['per share', 'eps'],
        'operating_income':   ['per share'],
    }

    # Value-magnitude sanity filters applied AFTER retrieval.
    # Catches mismatches that labels alone can't prevent (e.g. EPS value
    # of 8.87 matched as "shares_outstanding").
    METRIC_VALUE_BOUNDS = {
        'shares_outstanding': {'min': 100_000},   # no public co has <100K diluted shares
    }

    def __init__(self,
            cik: str,
            base_path: str = 'financial_data',
            filing_type: str = '10-K',
            years_statement: int = 5,
            persist_data: bool = False
        ):
        self.cik = str(cik).zfill(10)
        self.base_path = Path(base_path)
        self.filing_type = filing_type
        self.years_statement = years_statement
        self.persist_data = persist_data
        self.parquet_path = self.base_path / 'consolidated_financials.parquet'

        self._raw_data = self._fetch_and_transform_data()

        self._init_duckdb()

        if self.persist_data:
            self._save_to_parquet()

    def _fetch_and_transform_data(self):
        try:
            company = Company(self.cik)
            filings = company.get_filings(form=self.filing_type).latest(self.years_statement)

            if not filings:
                print(f"No {self.filing_type} filings found for {self.cik}")
                return pd.DataFrame()

            xbrls = XBRLS.from_filings(filings=filings)
            statements = {
                'Income Statement': xbrls.statements.income_statement().to_dataframe(),
                'Balance Sheet': xbrls.statements.balance_sheet().to_dataframe(),
                'Cash Flow': xbrls.statements.cashflow_statement().to_dataframe(),
            }
            all_records = []
            for stmt_name, df in statements.items():
                if df.empty: continue

                df = df.reset_index()
                if 'label' in df.columns:
                    df['concept_id'] = df['label'].astype(str).str.strip()
                else:
                    df['concept_id'] = df.iloc[:, 0].astype(str).str.strip()

                date_cols = [c for c in df.columns if re.match(r'^\d{4}-\d{2}-\d{2}$', str(c))]
                if not date_cols: continue

                melted = df.melt(
                    id_vars=['concept_id'],
                    value_vars=date_cols,
                    var_name='end_date',
                    value_name='value'
                )
                melted['statement_type'] = stmt_name
                all_records.append(melted)

            if not all_records:
                return pd.DataFrame()

            combined = pd.concat(all_records, ignore_index=True)
            combined['cik'] = self.cik
            combined['end_date'] = pd.to_datetime(combined['end_date'])
            combined['value'] = pd.to_numeric(combined['value'], errors='coerce')
            combined['form'] = self.filing_type

            return combined.dropna(subset=['value'])

        except Exception as e:
            print(f'error fetching dta for {self.cik}: {e}')
            return pd.DataFrame()

    def _init_duckdb(self):
        """Initialize DuckDB connection and register parquet file"""
        self.con = duckdb.connect(database=':memory:')
        if not self._raw_data.empty:
            self.con.register('financial_data', self._raw_data)
        else:
            # Create empty table structure if no data
            self.con.execute("""
                CREATE TABLE financial_data (
                    concept_id VARCHAR,
                    end_date TIMESTAMP,
                    value DOUBLE,
                    statement_type VARCHAR,
                    cik VARCHAR,
                    form VARCHAR
                )
            """)

    def _save_to_parquet(self):

        if self._raw_data.empty:
            return None

        self.base_path.mkdir(parents=True, exist_ok=True)

        try:
            if self.parquet_path.exists():
                existing_df = pd.read_parquet(self.parquet_path)
                combined = pd.concat([existing_df, self._raw_data], ignore_index=True)
                final_df = combined.drop_duplicates(
                    subset=['cik', 'concept_id', 'end_date', 'form'],
                    keep='last'
                    )
            else:
                final_df = self._raw_data

            final_df.to_parquet(self.parquet_path, index=False)
            print(f'save data for {self.cik} to {self.parquet_path}')

        except Exception as e:
            print(f'parquet not saved: {e}')

    def _get_aliases(self, metric_name: str) -> List[str]:
        return self.METRIC_ALIASES.get(metric_name, [metric_name])

    @staticmethod
    def _normalize(text: str) -> str:
        """Lowercase, strip punctuation/parens/dashes, collapse whitespace."""
        text = text.lower()
        text = re.sub(r"[\u2018\u2019'\"()\-,.]", " ", text)
        return re.sub(r"\s+", " ", text).strip()

    @staticmethod
    def _token_similarity(a: str, b: str) -> float:
        """
        Token-overlap similarity (Jaccard-like on words).
        Uses the *smaller* set as denominator so a short alias
        inside a long label still scores high.
        """
        tokens_a = set(a.split())
        tokens_b = set(b.split())
        if not tokens_a or not tokens_b:
            return 0.0
        intersection = tokens_a & tokens_b
        return len(intersection) / min(len(tokens_a), len(tokens_b))

    def _fuzzy_resolve_concepts(
        self,
        aliases: List[str],
        threshold: float = 0.60,
        statement_type: Optional[str] = None,
        exclude_patterns: Optional[List[str]] = None,
    ) -> List[str]:
        """
        Given a list of human-readable aliases, return actual concept_ids
        in the DB that fuzzy-match above `threshold`.
        Results ordered by alias priority (earlier alias = higher priority).

        Args:
            exclude_patterns: list of lowercase substrings.  Any DB concept
                              whose normalised label contains one of these
                              is silently skipped (prevents e.g. matching
                              "Earnings per share - diluted" for shares).
        """
        stmt_filter = f"AND statement_type = '{statement_type}'" if statement_type else ""
        try:
            db_concepts = self.con.sql(f"""
                SELECT DISTINCT concept_id
                FROM financial_data
                WHERE cik = '{self.cik}' AND form = '{self.filing_type}'
                {stmt_filter}
            """).df()
        except Exception:
            return []

        if db_concepts.empty:
            return []

        raw_labels = db_concepts['concept_id'].tolist()
        norm_to_raw = {self._normalize(lbl): lbl for lbl in raw_labels}
        norm_labels = list(norm_to_raw.keys())

        matched = []          # (priority, -score, raw_concept_id)
        already_matched = set()

        for priority, alias in enumerate(aliases):
            norm_alias = self._normalize(alias)
            best_score = 0.0
            best_raw = None

            for norm_lbl in norm_labels:
                if norm_lbl in already_matched:
                    continue
                # Skip labels that contain disqualifying substrings
                if exclude_patterns and any(ep in norm_lbl for ep in exclude_patterns):
                    continue
                score = self._token_similarity(norm_alias, norm_lbl)
                # Bonus: if one string fully contains the other, boost score
                if norm_alias in norm_lbl or norm_lbl in norm_alias:
                    score = max(score, 0.85)
                if score > best_score:
                    best_score = score
                    best_raw = norm_to_raw[norm_lbl]

            if best_raw and best_score >= threshold:
                matched.append((priority, -best_score, best_raw))
                already_matched.add(self._normalize(best_raw))

        matched.sort()  # by (priority, -score)
        return [raw for _, _, raw in matched]

    def get_time_series(
            self, metric_name: str,
            custom_aliases: Optional[List[str]] = None,
            statement_type: Optional[str] = None,
            fuzzy_threshold: float = 0.60,
        ) -> pd.DataFrame:
        """
        Get all values for a standardized concept over time.

        Strategy:
          1. Try exact match (fast, via cleaned aliases in SQL).
          2. If nothing found, fall back to fuzzy token-similarity
             matching against every concept_id in the DB.

        Args:
            statement_type: Restrict to 'Income Statement', 'Balance Sheet',
                            or 'Cash Flow'.  Auto-detected from METRIC_STATEMENT_TYPE
                            when not provided.
        """
        aliases = custom_aliases or self._get_aliases(metric_name)

        # auto-detect statement type to prevent cross-statement mismatches
        if statement_type is None:
            statement_type = self.METRIC_STATEMENT_TYPE.get(metric_name)

        stmt_filter = f"AND statement_type = '{statement_type}'" if statement_type else ""

        # --- PASS 1: exact match (original logic) ---
        cleaned_aliases = [
            a.replace("'", "").replace("\u2019", "").replace("-", "") 
            for a in aliases
        ]
        alias_list_str = "', '".join(cleaned_aliases)

        query = f"""
            SELECT 
                value, 
                end_date, 
                REPLACE(REPLACE(REPLACE(concept_id, '''', ''), '\u2019', ''), '-', '') AS clean_concept
            FROM financial_data
            WHERE cik = '{self.cik}'
            AND form = '{self.filing_type}'
            {stmt_filter}
            AND REPLACE(REPLACE(REPLACE(concept_id, '''', ''), '\u2019', ''), '-', '') IN ('{alias_list_str}')
            ORDER BY end_date DESC
            LIMIT {self.years_statement * 5}
        """
        try:
            df_all = self.con.sql(query).df()
        except Exception as e:
            print(f'error fetching time series for {metric_name}: {e}')
            df_all = pd.DataFrame()

        # --- PASS 2: fuzzy fallback ---
        if df_all.empty:
            exclude_patterns = self.METRIC_EXCLUDE_PATTERNS.get(metric_name, [])
            fuzzy_concepts = self._fuzzy_resolve_concepts(
                aliases, threshold=fuzzy_threshold,
                statement_type=statement_type,
                exclude_patterns=exclude_patterns,
            )
            if not fuzzy_concepts:
                return pd.DataFrame()

            escaped = [c.replace("'", "''") for c in fuzzy_concepts]
            in_clause = "', '".join(escaped)

            query = f"""
                SELECT value, end_date, concept_id AS clean_concept
                FROM financial_data
                WHERE cik = '{self.cik}'
                AND form = '{self.filing_type}'
                {stmt_filter}
                AND concept_id IN ('{in_clause}')
                ORDER BY end_date DESC
                LIMIT {self.years_statement * 5}
            """
            try:
                df_all = self.con.sql(query).df()
            except Exception as e:
                print(f'fuzzy query failed for {metric_name}: {e}')
                return pd.DataFrame()

            if df_all.empty:
                return pd.DataFrame()

            priority_map = {c: i for i, c in enumerate(fuzzy_concepts)}
            df_all['end_date'] = pd.to_datetime(df_all['end_date'])
            df_all['priority'] = df_all['clean_concept'].map(priority_map).fillna(999)
        else:
            df_all['end_date'] = pd.to_datetime(df_all['end_date'])
            priority_map = {alias: i for i, alias in enumerate(cleaned_aliases)}
            df_all['priority'] = df_all['clean_concept'].map(priority_map).fillna(999)

        df_all = df_all.sort_values(by=['end_date', 'priority'], ascending=[False, True])
        df_clean = df_all.drop_duplicates(subset=['end_date'], keep="first")

        # --- Value-magnitude filtering ---
        # Drop rows whose values fall outside the expected range for this metric
        # (e.g. shares_outstanding should never be < 100K for a public company)
        bounds = self.METRIC_VALUE_BOUNDS.get(metric_name, {})
        if bounds:
            if 'min' in bounds:
                before = len(df_clean)
                df_clean = df_clean[df_clean['value'].abs() >= bounds['min']]
                if len(df_clean) < before:
                    print(f"INFO: {metric_name} — filtered {before - len(df_clean)} "
                          f"rows below min={bounds['min']:,.0f} (likely per-share data)")
            if 'max' in bounds:
                df_clean = df_clean[df_clean['value'].abs() <= bounds['max']]

        return df_clean[['value', 'end_date']].head(self.years_statement)


    def get_latest_value(self, metric_name: str) -> float:
        """
        get the most recent value for a concept
        """
        df = self.get_time_series(metric_name)
        if not df.empty:
            return float(df['value'].iloc[0])
        return 0.0

    def get_income_statement_metrics(self) -> Dict:
        """
        retrive income statement metrics, for debugging raw data
        """
        return {
            'revenues': self.get_time_series('revenue'),
            'operating_income': self.get_time_series('operating_income'),
            'net_income': self.get_time_series('net_income'),
            'interest_expense': self.get_time_series('interest_expense'),
            'tax_expense': self.get_time_series('tax_expense'),
        }

    def get_balance_sheet_metrics(self) -> Dict:
        """
        retrive standardized balance sheet metrics, for debugging raw data
        """
        return {
            'cash': self.get_latest_value('cash'),
            'equity': self.get_latest_value('equity'),
            'long_term_debt': self.get_latest_value('long_term_debt'),
            'short_term_debt': self.get_latest_value('short_term_debt'),
        }

    def get_shares_outstanding(self) -> float:
        """
        special handling for shares, usually have different names
        """
        return self.get_latest_value('shares_outstanding')

    def close(self):
        """Close DuckDB connection"""
        self.con.close()


if __name__ == '__main__':
    # cik 104169 walmart
    # 1730168 broadcom
    #  2488 amd
    #  320193 apple
    # 1045810 nvidia
    # 1652044  google
    # 1018724 amazon
    process = FinancialDataProcessor(
        cik=1652044 ,
        years_statement= 4,
        filing_type='10-Q',
    )
